import marimo

__generated_with = "0.17.7"
app = marimo.App(width="medium")


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Test Data Generation
    The code in this notebook was used to generate the testattend.db and atts.csv files. The "atts.csv" contains fictional attendances, where one row represents a student attending one event.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Fictional Students
    Read a list of fictional students from the test-students.csv file. The student data was generated by the Microsoft Copilot AI chatbot. See the README.md file for the prompt and other information.
    """)
    return


@app.cell
def _(database, pathlib, pl):
    cur_folder = pathlib.Path.cwd()
    db_path = cur_folder / "testattend.db"
    dbase = database.DBase(db_path, create_new=(not db_path.exists()))
    if len(dbase.get_student_ids()) == 0:
        dbase.import_students_from_csv(cur_folder / "test-students.csv")
    students = pl.DataFrame([dict(row) for row in dbase.get_all_students()])
    students
    return (students,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Attendance Probabilities
    Some students attend almost every meeting and event, while others attend occassionally. For each student, we randomly generated an attendance probability and placed it in the *aprob* column.
    """)
    return


@app.cell
def _(np):
    rng = np.random.default_rng()
    return (rng,)


@app.cell
def _(np, rng, students):
    attendance_stats = students.with_columns(
        aprob=np.round(
            rng.triangular(left=0.2, mode=0.7, right=0.95, size=students.height), 2
        )
    )
    attendance_stats
    return (attendance_stats,)


@app.cell
def _(mo):
    mo.md(r"""
    ## Robotics Events
    We created a plausible team schedule running from the beginning of the school year to the first
    official robotics competition. Robotics events are classified as meetings, online meetings, competitions, outreach, and kickoff.
    """)
    return


@app.cell
def _(enum):
    class Event(enum.StrEnum):
        ONLINE = "online"
        MEETING = "meeting"
        OUTREACH = "outreach"
        COMPETITION = "competition"
        KICKOFF = "kickoff"
    return (Event,)


@app.cell
def _(Event, datetime, pl):
    # Set the start time based on the type of event. The start time is the hour of the day, using a 24-hour clock.
    _start_times = {
        Event.MEETING: 17,
        Event.ONLINE: 17,
        Event.KICKOFF: 6,
        Event.COMPETITION: 6,
        Event.OUTREACH: 8,
    }

    events = pl.DataFrame(
        [
            {"date": event[0], "type": event[1], "start": _start_times[event[1]]}
            for event in [
                (datetime.date(2025, 9, 4), Event.MEETING),
                (datetime.date(2025, 9, 11), Event.MEETING),
                (datetime.date(2025, 9, 18), Event.MEETING),
                (datetime.date(2025, 9, 25), Event.MEETING),
                (datetime.date(2025, 10, 2), Event.MEETING),
                (datetime.date(2025, 10, 4), Event.OUTREACH),
                (datetime.date(2025, 10, 5), Event.OUTREACH),
                (datetime.date(2025, 10, 9), Event.MEETING),
                (datetime.date(2025, 10, 11), Event.COMPETITION),
                (datetime.date(2025, 10, 12), Event.COMPETITION),
                (datetime.date(2025, 10, 16), Event.MEETING),
                (datetime.date(2025, 10, 23), Event.MEETING),
                (datetime.date(2025, 10, 30), Event.MEETING),
                (datetime.date(2025, 11, 6), Event.MEETING),
                (datetime.date(2025, 11, 13), Event.MEETING),
                (datetime.date(2025, 11, 20), Event.MEETING),
                (datetime.date(2025, 12, 4), Event.MEETING),
                (datetime.date(2025, 12, 11), Event.MEETING),
                (datetime.date(2025, 12, 18), Event.MEETING),
                (datetime.date(2026, 1, 3), Event.KICKOFF),
                (datetime.date(2026, 1, 5), Event.ONLINE),
                (datetime.date(2026, 1, 6), Event.MEETING),
                (datetime.date(2026, 1, 8), Event.MEETING),
                (datetime.date(2026, 1, 10), Event.MEETING),
                (datetime.date(2026, 1, 12), Event.ONLINE),
                (datetime.date(2026, 1, 13), Event.MEETING),
                (datetime.date(2026, 1, 15), Event.MEETING),
                (datetime.date(2026, 1, 17), Event.MEETING),
                (datetime.date(2026, 1, 19), Event.ONLINE),
                (datetime.date(2026, 1, 20), Event.MEETING),
                (datetime.date(2026, 1, 22), Event.MEETING),
                (datetime.date(2026, 1, 24), Event.MEETING),
                (datetime.date(2026, 1, 26), Event.ONLINE),
                (datetime.date(2026, 1, 27), Event.MEETING),
                (datetime.date(2026, 1, 29), Event.MEETING),
                (datetime.date(2026, 1, 31), Event.MEETING),
                (datetime.date(2026, 2, 1), Event.MEETING),
                (datetime.date(2026, 2, 2), Event.ONLINE),
                (datetime.date(2026, 2, 3), Event.MEETING),
                (datetime.date(2026, 2, 5), Event.MEETING),
                (datetime.date(2026, 2, 7), Event.MEETING),
                (datetime.date(2026, 2, 8), Event.MEETING),
                (datetime.date(2026, 2, 9), Event.ONLINE),
                (datetime.date(2026, 2, 10), Event.MEETING),
                (datetime.date(2026, 2, 12), Event.MEETING),
                (datetime.date(2026, 2, 14), Event.MEETING),
                (datetime.date(2026, 2, 15), Event.MEETING),
                (datetime.date(2026, 2, 16), Event.ONLINE),
                (datetime.date(2026, 2, 17), Event.MEETING),
                (datetime.date(2026, 2, 19), Event.MEETING),
                (datetime.date(2026, 2, 21), Event.MEETING),
                (datetime.date(2026, 2, 22), Event.MEETING),
                (datetime.date(2026, 2, 23), Event.ONLINE),
                (datetime.date(2026, 2, 24), Event.MEETING),
                (datetime.date(2026, 2, 26), Event.MEETING),
                (datetime.date(2026, 2, 28), Event.MEETING),
                (datetime.date(2026, 3, 1), Event.MEETING),
                (datetime.date(2026, 3, 2), Event.ONLINE),
                (datetime.date(2026, 3, 3), Event.MEETING),
                (datetime.date(2026, 3, 5), Event.MEETING),
                (datetime.date(2026, 3, 7), Event.COMPETITION),
                (datetime.date(2026, 3, 8), Event.COMPETITION),
            ]
        ]
    )
    return (events,)


@app.cell
def _(events):
    events
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Attendances
    For every student and event, we determine of the student attended that event by randomly sampling a Boolean variable with p(true) equal to the student's attendance probability.

    We assume that students record attendance anytime within a two hour period that starts 30 minutes prior to the event's scheduled starting time. The exact attendance time is randomly drawn from a triangular distrubtion with the mode equal to the scheduled start time.
    """)
    return


@app.cell
def _(datetime, relativedelta, rng):
    def sample_datetime(event_date, start_hour):
        seconds = rng.triangular(0, 1800, 7200)
        return datetime.datetime(
            event_date.year, event_date.month, event_date.day, hour=0
        ) + relativedelta.relativedelta(hours=start_hour, seconds=seconds)
    return (sample_datetime,)


@app.cell
def _(attendance_stats, events, rng, sample_datetime):
    atts= []
    for event in events.iter_rows(named=True):
        for student in attendance_stats.iter_rows(named=True):
            if rng.choice([True, False], p=[student["aprob"], 1 - student["aprob"]]):
                atts.append(
                    {
                        "student": student["student_id"],
                        "timestamp": sample_datetime(event["date"], event["start"]),
                    }
                )
    return (atts,)


@app.cell
def _(atts, pl):
    attsdf = pl.DataFrame(atts)
    attsdf
    return


@app.cell
def _():
    # attssdf.write_csv("atts.csv")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Warning
    Don't run the next cell more than once, or there will be duplicate attendance records. The cell takes about a minute to run.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Imports
    """)
    return


@app.cell(disabled=True)
def _():
    # for rap in raps:
    #     dbase.add_attendance_record(rap["student"], rap["timestamp"])
    return


@app.cell
def _():
    import datetime
    import enum
    import pathlib

    from dateutil import relativedelta
    import marimo as mo
    import numpy as np
    import polars as pl
    import seaborn as sns

    from irsattend.model import database
    return database, datetime, enum, mo, np, pathlib, pl, relativedelta


if __name__ == "__main__":
    app.run()
