qr_code_dir = "qr_codes"
email_sender_name = "IRS Attendance System"
# Following hash corresponds to 1318
# Was creaed with following code:
#   import hashlib
#   hashlib.sha256(b"1318").hexdigest()
password_hash = "095eaa09cd36d1f1e7a963c9ad618edab13f466882c9027ab81ffc18b0eb727e"
camera_number = 0  # Usually corresponds to front-facing camera.
smtp_server = ""
smtp_port = 465
smtp_username = ""
smtp_password = ""